### ISSUE TITLE
意图分类数据集

### ISSUE THREAD

**Issue by xxinfin** [zhihao-chen/QASystemOnMedicalGraph#1]
你好，我想问问，你的意图分类数据集的数据来源是什么？是从网上抓取的问答数据吗？

**Comment by red-frog** [comment]
> 您好，我问一下，运行python kbqa_test.py,报错，找不到merge_sgns_bigram_char300.txt文件，请问，这个文件中的内容是什么？

这个文件在这块, 可以下载下, 我也是找了一会找到的

![选区_001](https://user-images.githubusercontent.com/29301875/56860277-70007f80-69c7-11e9-94a5-dfc14e2077f3.png)

**Comment by xuningForAndroid** [comment]
好的，非常感谢

**Comment by Qinshimingyue23** [comment]
请问这个vocab.txt，disease_vocab.txt是什么意思，建图谱时也没有说明？

**Comment by Qinshimingyue23** [comment]
> 好的，非常感谢
请问这个vocab.txt，disease_vocab.txt是什么意思，建图谱时也没有说明？

**Comment by Qinshimingyue23** [comment]
> 好的，非常感谢

请问这个vocab.txt，disease_vocab.txt是什么意思，建图谱时也没有说明？

**Comment by wallon-ai** [comment]
请问一下neo4j用你提供的账号为什么登陆不上？

**Comment by unclesix06** [comment]
> > 您好，我问一下，运行python kbqa_test.py,报错，找不到merge_sgns_bigram_char300.txt文件，请问，这个文件中的内容是什么？
> 
> 这个文件在这块, 可以下载下, 我也是找了一会找到的
> 
> ![选区_001](https://user-images.githubusercontent.com/29301875/56860277-70007f80-69c7-11e9-94a5-dfc14e2077f3.png)

请问可以上提供一下这个merge_sgns_bigram_char300.txt文件的链接吗

**Comment by yujh123** [comment]
请问neo4j为什么上不去呀？是他自己的主机出了问题吗

**Comment by lcq950818** [comment]
> 你好，我想问问，你的意图分类数据集的数据来源是什么？是从网上抓取的问答数据吗？

**Comment by lcq950818** [comment]
麻烦请问一下，你是把博主的预训练词向量代码修改了然后实现对问句意图进行训练的吗？还有你的数据集是爬取的有关医疗对话的数据吗

**Comment by yujh123** [comment]
没有哎 我是直接用的博主训练好的模型  数据集也是用的博主发的数据集 你也在做关于知识图谱的问答系统吗




------------------ 原始邮件 ------------------
发件人: "lcq950818"<notifications@github.com>;
发送时间: 2019年10月8日(星期二) 下午3:54
收件人: "zhihao-chen/QASystemOnMedicalGraph"<QASystemOnMedicalGraph@noreply.github.com>;
抄送: "815720839"<815720839@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [zhihao-chen/QASystemOnMedicalGraph] 意图分类数据集 (#1)




麻烦请问一下，你是把博主的预训练词向量代码修改了然后实现对问句意图进行训练的吗？还有你的数据集是爬取的有关医疗对话的数据吗

**Comment by lcq950818** [comment]
> 没有哎 我是直接用的博主训练好的模型 数据集也是用的博主发的数据集 你也在做关于知识图谱的问答系统吗
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "lcq950818"<notifications@github.com>; 发送时间: 2019年10月8日(星期二) 下午3:54 收件人: "zhihao-chen/QASystemOnMedicalGraph"<QASystemOnMedicalGraph@noreply.github.com>; 抄送: "815720839"<815720839@qq.com>;"Comment"<comment@noreply.github.com>; 主题: Re: [zhihao-chen/QASystemOnMedicalGraph] 意图分类数据集 (#1) 麻烦请问一下，你是把博主的预训练词向量代码修改了然后实现对问句意图进行训练的吗？还有你的数据集是爬取的有关医疗对话的数据吗 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

对的，我也是知识问答，你是直接运行的博主的代码，那问题分类的效果怎么样

**Comment by yujh123** [comment]
我没有具体看他分类效果哎 就是直接拿来用 看程序跑通了也没有太管他  我不太知道怎么训练问句意图 您可以指点一下吗




------------------ 原始邮件 ------------------
发件人: "lcq950818"<notifications@github.com>;
发送时间: 2019年10月8日(星期二) 下午4:26
收件人: "zhihao-chen/QASystemOnMedicalGraph"<QASystemOnMedicalGraph@noreply.github.com>;
抄送: "815720839"<815720839@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [zhihao-chen/QASystemOnMedicalGraph] 意图分类数据集 (#1)



 
没有哎 我是直接用的博主训练好的模型 数据集也是用的博主发的数据集 你也在做关于知识图谱的问答系统吗
 …
 ------------------ 原始邮件 ------------------ 发件人: "lcq950818"notifications@github.com; 发送时间: 2019年10月8日(星期二) 下午3:54 收件人: "zhihao-chen/QASystemOnMedicalGraph"QASystemOnMedicalGraph@noreply.github.com; 抄送: "815720839"815720839@qq.com;"Comment"comment@noreply.github.com; 主题: Re: [zhihao-chen/QASystemOnMedicalGraph] 意图分类数据集 (#1) 麻烦请问一下，你是把博主的预训练词向量代码修改了然后实现对问句意图进行训练的吗？还有你的数据集是爬取的有关医疗对话的数据吗 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.
  
对的，我也是知识问答，你是直接运行的博主的代码，那问题分类的效果怎么样

**Comment by lcq950818** [comment]
> 我没有具体看他分类效果哎 就是直接拿来用 看程序跑通了也没有太管他 我不太知道怎么训练问句意图 您可以指点一下吗
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "lcq950818"<notifications@github.com>; 发送时间: 2019年10月8日(星期二) 下午4:26 收件人: "zhihao-chen/QASystemOnMedicalGraph"<QASystemOnMedicalGraph@noreply.github.com>; 抄送: "815720839"<815720839@qq.com>;"Comment"<comment@noreply.github.com>; 主题: Re: [zhihao-chen/QASystemOnMedicalGraph] 意图分类数据集 (#1) 没有哎 我是直接用的博主训练好的模型 数据集也是用的博主发的数据集 你也在做关于知识图谱的问答系统吗 … ------------------ 原始邮件 ------------------ 发件人: "lcq950818"notifications@github.com; 发送时间: 2019年10月8日(星期二) 下午3:54 收件人: "zhihao-chen/QASystemOnMedicalGraph"QASystemOnMedicalGraph@noreply.github.com; 抄送: "815720839"815720839@qq.com;"Comment"comment@noreply.github.com; 主题: Re: [zhihao-chen/QASystemOnMedicalGraph] 意图分类数据集 (#1) 麻烦请问一下，你是把博主的预训练词向量代码修改了然后实现对问句意图进行训练的吗？还有你的数据集是爬取的有关医疗对话的数据吗 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread. 对的，我也是知识问答，你是直接运行的博主的代码，那问题分类的效果怎么样 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

好尴尬，我也不会，我也是刚开始，正在寻找方法，不好意思了

**Comment by pkuzhangyao** [comment]
> 我没有具体看他分类效果哎 就是直接拿来用 看程序跑通了也没有太管他 我不太知道怎么训练问句意图 您可以指点一下吗
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "lcq950818"<notifications@github.com>; 发送时间: 2019年10月8日(星期二) 下午4:26 收件人: "zhihao-chen/QASystemOnMedicalGraph"<QASystemOnMedicalGraph@noreply.github.com>; 抄送: "815720839"<815720839@qq.com>;"Comment"<comment@noreply.github.com>; 主题: Re: [zhihao-chen/QASystemOnMedicalGraph] 意图分类数据集 (#1) 没有哎 我是直接用的博主训练好的模型 数据集也是用的博主发的数据集 你也在做关于知识图谱的问答系统吗 … ------------------ 原始邮件 ------------------ 发件人: "lcq950818"notifications@github.com; 发送时间: 2019年10月8日(星期二) 下午3:54 收件人: "zhihao-chen/QASystemOnMedicalGraph"QASystemOnMedicalGraph@noreply.github.com; 抄送: "815720839"815720839@qq.com;"Comment"comment@noreply.github.com; 主题: Re: [zhihao-chen/QASystemOnMedicalGraph] 意图分类数据集 (#1) 麻烦请问一下，你是把博主的预训练词向量代码修改了然后实现对问句意图进行训练的吗？还有你的数据集是爬取的有关医疗对话的数据吗 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread. 对的，我也是知识问答，你是直接运行的博主的代码，那问题分类的效果怎么样 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

你好，我也在做知识图谱问答，可以交流一下嘛，qq:437290013

**Comment by wangzherongyaoaaaa** [comment]
> > 您好，我问一下，运行python kbqa_test.py,报错，找不到merge_sgns_bigram_char300.txt文件，请问，这个文件中的内容是什么？
> 
> 这个文件在这块, 可以下载下, 我也是找了一会找到的
> 
> ![选区_001](https://user-images.githubusercontent.com/29301875/56860277-70007f80-69c7-11e9-94a5-dfc14e2077f3.png)


你好，请问下merge_sgns_bigram_char300.txt文件在哪儿下载，你发的图加载不了，谢谢

**Comment by alaleila** [comment]
https://pan.baidu.com/s/14JP1gD7hcmsWdSpTvA3vKA

**Comment by alaleila** [comment]
bzip2 -d merge_sgns_bigram_char300.txt.bz2

**Comment by XiaoyuanMax** [comment]
有一起学习这个项目的小伙伴么，欢迎联系我772538496@qq.com，互相帮助一起学习！

**Comment by guanyy99** [comment]
运行python kbqa_test.py,有以下提示但又不知道错在哪里了，我小伙伴可以帮我看看吗


Traceback (most recent call last):
  File "E:/zhihuiyiliao/venv/kbqa_test.py", line 24, in <module>
    handler = KBQA()
  File "E:/zhihuiyiliao/venv/kbqa_test.py", line 7, in __init__
    self.extractor = EntityExtractor()#调用问题分类函数，可以链接追踪
  File "E:\zhihuiyiliao\venv\entity_extractor.py", line 23, in __init__
    self.tfidf_model = joblib.load(self.tfidf_path)
  File "E:\python\lib\site-packages\joblib\numpy_pickle.py", line 592, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "E:\python\lib\site-packages\joblib\numpy_pickle.py", line 511, in _unpickle
    obj = unpickler.load()
  File "E:\python\lib\pickle.py", line 1088, in load
    dispatch[key[0]](self)
KeyError: 0

Process finished with exit code 1
