### ISSUE TITLE
ModuleNotFoundError: No module named 'sklearn.externals.joblib'

### ISSUE THREAD

**Issue by yefeister** [zhihao-chen/QASystemOnMedicalGraph#12]
运行kbqa_test.py,出现错误：ModuleNotFoundError: No module named 'sklearn.externals.joblib' in module pickle.py. 我的版本是python3.10.
Traceback (most recent call last):
  File "C:\Users\Documents\QASystemOnMedicalGraph-master\kbqa_test.py", line 27, in <module>
    handler = KBQA()
  File "C:\Users\Documents\QASystemOnMedicalGraph-master\kbqa_test.py", line 10, in __init__
    self.extractor = EntityExtractor()
  File "C:\Users\Documents\QASystemOnMedicalGraph-master\entity_extractor.py", line 23, in __init__
    self.tfidf_model = joblib.load(self.tfidf_path)
  File "C:\Users\Documents\QASystemOnMedicalGraph-master\venv\lib\site-packages\joblib\numpy_pickle.py", line 587, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "C:\Users\Documents\QASystemOnMedicalGraph-master\venv\lib\site-packages\joblib\numpy_pickle.py", line 506, in _unpickle
    obj = unpickler.load()
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\pickle.py", line 1213, in load
    dispatch[key[0]](self)
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\pickle.py", line 1529, in load_global
    klass = self.find_class(module, name)
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\pickle.py", line 1580, in find_class
    __import__(module, level=0)
ModuleNotFoundError: No module named 'sklearn.externals.joblib'

**Comment by 123456jjaWHO** [comment]
pip install Scikit-learn==0.20.4 -i https://pypi.tuna.tsinghua.edu.cn/simple

**Comment by 18118019819** [comment]
现在好像直接pip install joblib了，不包含在sklearn的包里了，然后直接import joblib

**Comment by J-Jzf** [comment]
请问解决了嘛，怎么解决的，我也是这个问题

**Comment by kokyouu** [comment]
> 现在好像直接pip install joblib了，不包含在sklearn的包里了，然后直接import joblib

直接import joblib好像也会报错ModuleNotFoundError: No module named 'sklearn'

**Comment by CodeDuoGun** [comment]
> pip install Scikit-learn==0.20.4 -i https://pypi.tuna.tsinghua.edu.cn/simple
which version of python you chose? ,i tried your method ,but not work.

**Comment by yanyanyan100** [comment]
> > 现在好像直接pip install joblib了，不包含在sklearn的包里了，然后直接import joblib
> 
> 直接import joblib好像也会报错ModuleNotFoundError: No module named 'sklearn'

请问解决了吗？我也是这个问题

**Comment by Yanxians** [comment]
直接import joblib也不行，因为model里存的两个模型是用旧版Sklearn保存的，pickle读取的时候还是会用旧模块读取，所以还会报错。
